---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-
namespace: dev

patches:
- patch: |-
    - op: replace
      path: /spec/parentRefs/0/name
      value: cafe-gateway
    - op: replace
      path: /spec/parentRefs/0/namespace
      value: default  
  target:
    kind: HTTPRoute
    name: wiki-route

commonLabels:
  environment: dev
