---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: playground-role
  namespace: wiki
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: playground-rolebinding
  namespace: wiki
subjects:
- kind: ServiceAccount
  name: playground
  namespace: wiki
roleRef:
  kind: Role
  name: playground-role
  apiGroup: rbac.authorization.k8s.io

